[project]
name = "persistent"
version = "0.1.0"
description = "Pulumi script for deployment of production infrastructure."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pulumi-docker>=4.8.2",
    "pulumi-gcp>=8.41.1",
    "pulumi-std>=2.2.0",
    "pulumi>=3.191.0",
]
