exclude: "(^docs/|(.*)tsv|(.*)csv|(.*).sh)"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=25000"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-lock
        files: ./services/extract/
      - id: uv-lock
        files: ./services/transform/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: ["--verbose"]
        files: ^services/extract/src/pipeline/
      - id: ruff-format
        args: ["--verbose"]
        files: ^services/extract/src/pipeline/
      - id: ruff-check
        args: ["--verbose"]
        files: ^services/transform/src/clean_raw/
      - id: ruff-format
        args: ["--verbose"]
        files: ^services/transform/src/clean_raw/
      - id: ruff-check
        args: ["--verbose"]
        files: ^services/map/src/map_clean/
      - id: ruff-format
        args: ["--verbose"]
        files: ^services/map/src/map_clean/

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
