name: CI

on:
  push:
  pull_request:
    branches:
      - 'main'

env:
  SRC_DIR: scrapers
  TEST_DIR: test

jobs:
  style_lint_and_type_check:
    name: style lint and type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip3 install --upgrade pip
          pip3 install flake8 mypy black types-PyYAML
      - run: |
          python3 -m black --check $TEST_DIR
          python3 -m flake8 $SRC_DIR # $TEST_DIR # should also run against scrapers but that will need more cleanup
          python3 -m mypy $TEST_DIR --follow-imports=skip --disallow-untyped-defs
  secrets_check:
    name: check secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip3 install --upgrade pip
          pip3 install detect-secrets
      - run: |
          set -e
          detect-secrets scan $TEST_DIR | python3 -c '
          import sys, json
          sys.exit(len(json.load(sys.stdin)["results"]))
          '
          if [ $? -ne 0 ]; then
            echo "STOP : [ $? ] secrets detected"
            exit 1
          fi
          echo "No secrets detected"

# Run mypy on diff
# git diff --name-only --diff-filter=d origin/main -- '*.py' | xargs mypy --follow-imports=skip --disallow-untyped-defs
